version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /mnt/nrcs/isgs:/data
    environment:
      DOCKER_JUPYTER_CONTAINER: jterstriep/geo-notebook:pyviz
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:lidar.ncsa.illinois.edu"
    restart: on-failure

  minio-data:
    image: minio/minio
    container_name: minio-data
    command: "server /data" 
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:lidar.ncsa.illinois.edu;PathPrefixStrip:/data"
      - "traefik.port=9000"
    volumes:
      - /mnt/nrcs/dap:/data
      - /mnt/nrcs/minio:/root/.minio

#  jupyterlab:
#    build: jupyterlab
#    image: jupyterlab_img
#    container_name: jupyterlab-throaway
#    network_mode: none
#    command: echo

  reverse-proxy:
    image: traefik:v1.7
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - ${CERTS}:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

#  oauth2_server:
#    image: defeo/cas2oauth2bridge
#    container_name: c2o2b
#    volumes:
#      - ./oauth2/config.js:/home/node/config.js
#    labels:
#      - "traefik.enable=true"
#      - "traefik.frontend.rule=Host:lidar.ncsa.illinois.edu;PathPrefixStrip:/c2o2b/"
#    restart: on-failure

volumes:
  jupyterhub_data:
